import type { Metadata } from 'next';
import localFont from 'next/font/local';

import { Box } from '@mui/material';

import './globals.css';
import ThemeProviderWrapper from '../theme/theme_provider';
import ReduxProvider from '../store/provider';
import ResetReduxProvider from '../hooks/useResetReduxState';
import Navbar from '../components/navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <ReduxProvider>
        <ResetReduxProvider>
          <ThemeProviderWrapper>
            <body>
              <Navbar />
              <Box
                sx={{
                  minHeight: '100vh',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  background: 'linear-gradient(45deg, #D3D3D3 30%, #E8E8E8 90%)',
                  padding: 3,
                }}
              >
                {children}
              </Box>
            </body>
          </ThemeProviderWrapper>
        </ResetReduxProvider>
      </ReduxProvider>
    </html>
  );
}
